# .github/workflows/main.yml
name: generate pacman game
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # daily at 2:00 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate pacman graph
        run: npm install -g pacman-contribution-graph && pacman-contribution-graph --username VishalRaut2106 --output output/
      - name: Commit and push
        run: |
          git config --global user.email "pacman-bot@example.com"
          git config --global user.name "Pacman Bot"
          git add output/
          git commit -m "Update Pac-Man graph"
          git push
